apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: weavesocks
spec:
  replicas: 1
  imagePullSecrets:
    - coherence-k8s-operator-development-secret
    - ocr-k8s-operator-development-secret
  images:
    coherence:
      image: iad.ocir.io/odx-stateservice/test/coherence:14.1.1.0.0-b74871
#    fluentd:
#      application:
#        configFile: /conf/fluentd-cloud.conf
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  logging:
    configFile: logging.properties
#    fluentdEnabled: true
  ports:
    - name: metrics
      port: 7001
  maxHeap: 256m
  resources:
    limits:
      cpu: 2
  roles:
    - role: carts
      images:
        userArtifacts:
          image: weavesocks/carts:2.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
        - name: http
          port: 7001
          service:
            name: carts
            port: 80
    - role: catalogue
      images:
        userArtifacts:
          image: weavesocks/catalogue:1.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: catalogue
            port: 80
    - role: payment
      images:
        userArtifacts:
          image: weavesocks/payment:3.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
    - role: shipping
      images:
        userArtifacts:
          image: weavesocks/shipping:2.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
    - role: orders
      images:
        userArtifacts:
          image: weavesocks/orders:3.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: orders
            port: 80
    - role: user
      images:
        userArtifacts:
          image: weavesocks/user:2.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
        - name: http
          port: 7001
          service:
            name: user
            port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: weaveworksdemos/front-end:0.3.12
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
  selector:
    name: front-end
