apiVersion: coherence.oracle.com/v1
kind: CoherenceCluster
metadata:
  name: weavesocks
spec:
  replicas: 1
  imagePullSecrets:
    - coherence-k8s-operator-development-secret
    - ocr-k8s-operator-development-secret
  images:
    coherence:
      image: iad.ocir.io/odx-stateservice/test/coherence:14.1.1.0.0-b74871
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
  logging:
    configFile: logging.properties
  ports:
    - name: metrics
      port: 7001
  maxHeap: 256m
  resources:
    limits:
      cpu: 2
  roles:
    - role: carts
      images:
        userArtifacts:
          image: weavesocks/carts:1.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: carts
            port: 80
    - role: catalogue
      images:
        userArtifacts:
          image: weavesocks/catalogue:1.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: catalogue
            port: 80
    - role: payment
      images:
        userArtifacts:
          image: weavesocks/payment:2.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
          service:
            name: payment
    - role: shipping
      images:
        userArtifacts:
          image: weavesocks/shipping:2.0.0
          imagePullPolicy: Always
      ports:
        - name: grpc
          port: 1408
          service:
            name: shipping
    - role: orders
      images:
        userArtifacts:
          image: weavesocks/orders:2.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: orders
            port: 80
    - role: user
      images:
        userArtifacts:
          image: weavesocks/user:1.0.0
          imagePullPolicy: Always
      ports:
        - name: http
          port: 7001
          service:
            name: user
            port: 80
    - role: front-end
      graalApplicationType: node
      main:
        class: server.js
      env:
        - name: SESSION_COHERENCE
          value: "true"
      images:
        coherence:
          image: weavesocks/front-end:2.0.0
      ports:
        - name: http
          port: 7001
          service:
            type: NodePort
            port: 80
